const { onCall } = require('firebase-functions/v2/https');
const admin = require('firebase-admin');
const logger = require('firebase-functions/logger');

const db = admin.firestore();

/**
 * Process AP Approval Status
 * Updates shipments to mark them as AP-approved when charges are approved through AP Processing
 */
const processAPApproval = onCall({
    cors: true,
    maxInstances: 5,
    timeoutSeconds: 60
}, async (request) => {
    try {
        const { 
            shipmentIds, 
            apProcessingId, 
            carrierInvoiceRef,
            approvalType = 'ap_processing',
            overrideExceptions = false,
            approvalNotes = '',
            extractedShipmentsData = [] // 🔧 NEW: Store extracted cost data for final approval
        } = request.data;
        
        const userId = request.auth?.uid;
        const userEmail = request.auth?.email;

        if (!userId) {
            throw new Error('Authentication required');
        }

        if (!shipmentIds || !Array.isArray(shipmentIds) || shipmentIds.length === 0) {
            throw new Error('Shipment IDs array is required');
        }

        logger.info('📋 Processing AP approval for shipments', {
            shipmentCount: shipmentIds.length,
            apProcessingId,
            userId,
            overrideExceptions
        });

        const results = [];
        const errors = [];

        // Process each shipment
        for (const shipmentId of shipmentIds) {
            try {
                const result = await processShipmentAPApproval(
                    shipmentId, 
                    userId, 
                    userEmail, 
                    apProcessingId,
                    carrierInvoiceRef,
                    overrideExceptions,
                    approvalNotes,
                    extractedShipmentsData // Pass extractedShipmentsData to processShipmentAPApproval
                );
                results.push(result);
            } catch (error) {
                logger.error(`❌ Failed to approve AP for shipment ${shipmentId}:`, error);
                errors.push({
                    shipmentId,
                    error: error.message
                });
            }
        }

        const successCount = results.filter(r => r.success).length;
        const failureCount = errors.length;

        return {
            success: failureCount === 0,
            processedCount: shipmentIds.length,
            successCount: successCount,
            failureCount: failureCount,
            results: results,
            errors: errors,
            message: `Processed AP approval for ${successCount}/${shipmentIds.length} shipments`
        };

    } catch (error) {
        logger.error('❌ AP approval processing error:', error);
        return {
            success: false,
            error: error.message
        };
    }
});

/**
 * Process AP approval for a single shipment
 */
async function processShipmentAPApproval(shipmentId, userId, userEmail, apProcessingId, carrierInvoiceRef, overrideExceptions, approvalNotes, extractedShipmentsData) {
    // 🔧 CRITICAL FIX: ALWAYS query by shipmentID field, NEVER use document ID
    logger.info(`🔍 Querying shipment by shipmentID field: ${shipmentId}`);
    const shipmentQuery = await db.collection('shipments')
        .where('shipmentID', '==', shipmentId)
        .limit(1)
        .get();
        
    if (shipmentQuery.empty) {
        throw new Error(`Shipment ${shipmentId} not found in database`);
    }
    
    const shipmentDoc = shipmentQuery.docs[0];
    const documentId = shipmentDoc.id;
    logger.info(`✅ Found shipment by shipmentID field. Document ID: ${documentId}`);

    const shipmentData = shipmentDoc.data();

    // Check if shipment can be AP approved
    const canApprove = await validateAPApproval(shipmentData);
    if (!canApprove.allowed) {
        throw new Error(canApprove.reason);
    }

    // Prepare AP approval update
    const apApprovalData = {
        chargeStatus: {
            status: 'ap_processed', // 🔧 FIXED: Changed from 'approved' to 'ap_processed'
            approvalType: 'ap_processing',
            approvedBy: userEmail || 'system', // 🔧 FIXED: Handle undefined userEmail
            approvedAt: admin.firestore.FieldValue.serverTimestamp(),
            approvedByUserId: userId || null, // 🔧 FIXED: Handle undefined userId
            overrideExceptions: overrideExceptions,
            approvalNotes: approvalNotes || '',
            apProcessingId: apProcessingId || null,
            carrierInvoiceRef: carrierInvoiceRef || null,
            autoGenerated: false,
            requiresFinalApproval: true // 🔧 NEW: Indicates needs final approval in charges table
        },
        
        // Track AP processing approval separately
        apApproval: {
            status: 'approved',
            approvedAt: admin.firestore.FieldValue.serverTimestamp(),
            approvedBy: userEmail || 'system', // 🔧 FIXED: Handle undefined userEmail
            apProcessingId: apProcessingId || null,
            carrierInvoiceRef: carrierInvoiceRef || null,
            overrideExceptions: overrideExceptions,
            approvalNotes: approvalNotes || ''
        },
        
        // 🔧 NEW: Store extracted cost data for final approval step
        apExtractedCosts: extractedShipmentsData.find(item => 
            item.shipmentId === shipmentId || item.shipmentId === shipmentData.shipmentID
        )?.extractedCosts || null,
        
        apInvoiceData: extractedShipmentsData.find(item => 
            item.shipmentId === shipmentId || item.shipmentId === shipmentData.shipmentID
        )?.invoiceData || null,
        
        // Track approval in status history
        [`statusHistory.${Date.now()}`]: {
            status: shipmentData.status || 'unknown',
            timestamp: admin.firestore.FieldValue.serverTimestamp(),
            note: overrideExceptions ? 
                `AP Processing approved with exception override - ready for final charge approval: ${approvalNotes}` :
                `AP Processing approved - ready for final charge approval: ${approvalNotes}`,
            updatedBy: userEmail || 'system', // 🔧 FIXED: Handle undefined userEmail
            type: 'ap_charges_processed', // 🔧 CHANGED: from 'ap_charges_approved' to 'ap_charges_processed'
            changes: {
                apProcessingId: apProcessingId,
                carrierInvoiceRef: carrierInvoiceRef,
                overrideExceptions: overrideExceptions,
                requiresFinalApproval: true
            }
        }
    };

    // If overriding exceptions, mark them as resolved
    if (overrideExceptions && shipmentData.exceptionStatus?.hasExceptions) {
        apApprovalData.exceptionStatus = {
            ...shipmentData.exceptionStatus,
            resolvedAt: admin.firestore.FieldValue.serverTimestamp(),
            resolvedBy: userEmail,
            resolutionMethod: 'ap_override',
            resolutionNotes: approvalNotes
        };
    }

    // Update shipment document
    await db.collection('shipments').doc(documentId).update(apApprovalData);

    // Log AP approval event
    await logAPApprovalEvent(documentId, shipmentId, userEmail, apProcessingId, carrierInvoiceRef);

    return {
        success: true,
        shipmentId: documentId,
        shipmentID: shipmentId,
        apProcessingId: apProcessingId,
        newStatus: 'ap_processed', // 🔧 CHANGED: from 'ap_approved' to 'ap_processed'
        message: 'AP processing completed - charges ready for final approval'
    };
}

/**
 * Validate if shipment can be AP approved
 */
async function validateAPApproval(shipmentData) {
    // Check if shipment is cancelled
    if (shipmentData.status === 'cancelled' || shipmentData.status === 'canceled') {
        return {
            allowed: false,
            reason: 'Cannot approve AP charges for cancelled shipments'
        };
    }

    // Check if already AP processed
    if (shipmentData.chargeStatus?.status === 'ap_processed' && 
        shipmentData.chargeStatus?.approvalType === 'ap_processing') {
        return {
            allowed: false,
            reason: 'Charges already processed through AP Processing and ready for final approval'
        };
    }

    // Check if already fully approved
    if (shipmentData.chargeStatus?.status === 'approved') {
        return {
            allowed: false,
            reason: 'Charges already fully approved'
        };
    }

    return {
        allowed: true,
        reason: 'Validation passed'
    };
}

/**
 * Log AP approval event for audit trail
 */
async function logAPApprovalEvent(shipmentId, shipmentID, userEmail, apProcessingId, carrierInvoiceRef) {
    try {
        await db.collection('apApprovalLog').add({
            shipmentId: shipmentId || null,
            shipmentID: shipmentID || null,
            approvedBy: userEmail || 'system', // 🔧 FIXED: Handle undefined userEmail
            approvedAt: admin.firestore.FieldValue.serverTimestamp(),
            apProcessingId: apProcessingId || null,
            carrierInvoiceRef: carrierInvoiceRef || null,
            action: 'ap_approval'
        });
    } catch (error) {
        logger.warn('Failed to log AP approval event:', error);
    }
}

module.exports = { processAPApproval }; 